dist: trusty
language: cpp
cache: ccache
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake
    - ccache
    - libtbb-dev
install:
- bash build_occt.sh
script:
- make package
deploy:
  provider: releases
  file: dist/occt-7.3.0-${TRAVIS_OS_NAME}.tgz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: antonymarion/occt_builder
  api-key:
    secure: X4OZvLjobuSpRq6UtYnKRmQIHC7ePJ0BmoikQibfCjRcPCZoFbCBJb46yTrQUX44FWVLWiuO89XleOC7EgAdtdGIuN7QWQkOsvDhKxV33n5Mfv2btPRDuBYY0Xsuto6rhL3EtQeori2kHmpVbG8laqiT0ouBnRu0ZpaRAoR8NJYHpnpIkmBuHlwgWfAFWiLj29eiPuDx9FluF7FvbGgHc/riKCln893faBTKx9L+silgx+SE7M7sjOD0fdavdn6QYUUn8m3eqwueRyGkdFp1agQgCnfeqn7qxmOM/R6AxwSGJvPCUvBH2vLcI3dBhfc2+lvHwo/MprJLmHSjgk8a5Ua28tgpi96zNtmL8+AsjM/dBVkRBAQlSoK+hZ4Ged9HtDQYpQzVltUXYprZRC8H3q+wiAZ4l5N1Gi91Q6+O4tbeoZTEVzdiyljjQOxVXpf7D5uf2CvL5df3TImfq5Iym3lPIopH9caHP6mo4lUl5rjH/G1n9T5vjlgsuSb6QvOgmQa3RfdKUERArgj/Bv2sg+4cydEt0HywIbwHrnosQjzrQQagWJzYAe2ZYUnnkLViP0HhfQtni+6JUl4nHDayKeoiH4iwWYVyWFkEMVsNsuDJlVRQfEF0EqsFCT/2yQKZNUT4i7q3C+mG2AYPjE4XpofOOUif6lGqwQ7tcAyVDh8=
env:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: QLn52YaMzobrIzERHGZ3AL32uLr6RN9FfkMwenFOA8SXjGecZ8WXBZq+xg3QLwW/rRb4FWO2Dd83Djrbj5X+NfW82H6YXoLRWKmTxRfqeIJ47BdXi8DYXLrEAOZs6LcIcJ/A2oM64UIJtb4gKnKze3dfxGAIciBQA+tjNqfc6kvtzUGnXDJ/9HSOG6YbqZiZtUtPTK1f5OElhPFeQL1OkqMLQp5E0lqzQG/+b0Rkx6AX+kDSga7vSmG7CWjXanHjaeCvy6lIAAzLpRWuE43oN0USWMAynAlZ9bWt2Fj7KNv63wUmIgK2ykOFCGZK15HEJjoT4TVmEa6FH6A76KLUFm/sSEgLpGe8C3mWpIjQdoLQbw5xEl1bFWfM/3Yyg7Qx/b6bAnuhnocqsEd+eoYE80KdxC2CUziRSq0dwzhvWT92SJKyuOVHPMnij/vGKeRup4jcuzdRwwyibD0osQG3JiPkSwVeQQ4gtPHvRdfo8I/8KV55UX0wdhq29HMkh7o4bBMd/ywiw5LZb5yXPhIXGfUn2hh1ODo+N7zb3NZt03TTE/igFL1exZIn6eiSrTzcUtkEiQKrSnVTq1Afom2slOoTpE+LtrWPKIlXde6fF50wKvu6x8KpwmikZUMsCNdTDGI9Xfh3Zx0O+PsEn7/HkRv8Wy5E3hGTn1piksypqXU=