dist: trusty
language: cpp
cache: ccache
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake
    - ccache
    - libtbb-dev
install:
- bash build_occt.sh
script:
- make package
deploy:
  provider: releases
  api_key:
    secure: "cE8cdnSR+VaoEfhGDN5SH0VWFMzN762V4Mq486HaJ+klfxs5HqgzcODDZAiTi6zAdwPbslzryfitFWiTzIcmm/giROCq+DZjzv+bsrtliyg77Jg6ZdE2PozovaeQWCzm3ffzfxoq+X15zSgBgEcB5o39mlNvyF7EnzmJuNxJbZdTOZfDksqCYMMaxWSmNdR9xbMkmXFJ9tKiyxe24p7BQ6tJU5VVByLcq1/tKO3Opc31Zpi5ZQD225lcLBE0JCpy4+eeTcO2QRltgNDigBVWaTuoqP6qtt3grtN2SLbQS7gZbj15qaKqQfrQ7WzfusqsR79Ty1oaWFLLXXJVaxTdECqvwnavfwZdmFt/R21JBj7K054rncT4HD6ft7yioY6a57jDAf/den/DkGHj2VFkY3iNLFwOC8wiYqJAqbAspEQNp80njffpjm0WT/4dtTq71zLez9N33sMmLPnhUtmOrCk6BTNA7mqH3qhHrjA3oDui33XkWHVxHlugi1yBDXIWQ5npxEI/AwHYHVCC2qDcF+7/ccxX9FvvwInYFFMisVrlx1fayivTt9cSQRd4fuWRL1UVNPuCVxu6I3wj0MjA4yQ1LgHqMqVxz1A3hEhxXF7p6aRvBrws1LphdqRSZe/e6ptXLoNfmGiXd5+js2YmdM9PIE3Q6lHDHcnD0+nPpuo="
  file: dist/occt-7.2.0-${TRAVIS_OS_NAME}.tgz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: antonymarion/occt_builder
